# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminHome.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminHome(object):
    def setupUi(self, AdminHome):
        AdminHome.setObjectName("AdminHome")
        AdminHome.resize(1200, 600)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(AdminHome)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridWidget = QtWidgets.QWidget(AdminHome)
        self.gridWidget.setObjectName("gridWidget")
        self.buttonlayout = QtWidgets.QGridLayout(self.gridWidget)
        self.buttonlayout.setObjectName("buttonlayout")
        self.addBookButton = QtWidgets.QPushButton(self.gridWidget)
        self.addBookButton.setEnabled(True)
        self.addBookButton.setMaximumSize(QtCore.QSize(100, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addBookButton.setFont(font)
        self.addBookButton.setObjectName("addBookButton")
        self.buttonlayout.addWidget(self.addBookButton, 0, 0, 1, 1)
        self.dropBookButton = QtWidgets.QPushButton(self.gridWidget)
        self.dropBookButton.setMaximumSize(QtCore.QSize(100, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dropBookButton.setFont(font)
        self.dropBookButton.setObjectName("dropBookButton")
        self.buttonlayout.addWidget(self.dropBookButton, 1, 0, 1, 1)
        self.userManageButton = QtWidgets.QPushButton(self.gridWidget)
        self.userManageButton.setMaximumSize(QtCore.QSize(100, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.userManageButton.setFont(font)
        self.userManageButton.setObjectName("userManageButton")
        self.buttonlayout.addWidget(self.userManageButton, 2, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.gridWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Hlayout1_2 = QtWidgets.QHBoxLayout()
        self.Hlayout1_2.setObjectName("Hlayout1_2")
        self.searchEdit_2 = QtWidgets.QLineEdit(AdminHome)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.searchEdit_2.setFont(font)
        self.searchEdit_2.setObjectName("searchEdit_2")
        self.Hlayout1_2.addWidget(self.searchEdit_2)
        self.searchButton_2 = QtWidgets.QPushButton(AdminHome)
        self.searchButton_2.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.searchButton_2.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/syx/.designer/images/search.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.searchButton_2.setIcon(icon)
        self.searchButton_2.setObjectName("searchButton_2")
        self.Hlayout1_2.addWidget(self.searchButton_2)
        self.comboBox_2 = QtWidgets.QComboBox(AdminHome)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 32))
        self.comboBox_2.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.Hlayout1_2.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.Hlayout1_2)
        self.tableWidget = QtWidgets.QTableWidget(AdminHome)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalWidget = QtWidgets.QWidget(AdminHome)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.horizontalWidget)
        self.widget_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.Hlayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.Hlayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.Hlayout_2.setObjectName("Hlayout_2")
        self.jumpToLabel_2 = QtWidgets.QLabel(self.widget_2)
        self.jumpToLabel_2.setObjectName("jumpToLabel_2")
        self.Hlayout_2.addWidget(self.jumpToLabel_2)
        self.pageEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        self.pageEdit_2.setMaximumSize(QtCore.QSize(32, 16777215))
        self.pageEdit_2.setObjectName("pageEdit_2")
        self.Hlayout_2.addWidget(self.pageEdit_2)
        self.pageLabel_2 = QtWidgets.QLabel(self.widget_2)
        self.pageLabel_2.setObjectName("pageLabel_2")
        self.Hlayout_2.addWidget(self.pageLabel_2)
        self.jumpToButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.jumpToButton_2.setObjectName("jumpToButton_2")
        self.Hlayout_2.addWidget(self.jumpToButton_2)
        self.prevButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.prevButton_2.setObjectName("prevButton_2")
        self.Hlayout_2.addWidget(self.prevButton_2)
        self.backButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.backButton_2.setObjectName("backButton_2")
        self.Hlayout_2.addWidget(self.backButton_2)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.horizontalWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(AdminHome)
        QtCore.QMetaObject.connectSlotsByName(AdminHome)

    def retranslateUi(self, AdminHome):
        _translate = QtCore.QCoreApplication.translate
        AdminHome.setWindowTitle(_translate("AdminHome", "欢迎使用图书馆管理系统"))
        self.addBookButton.setText(_translate("AdminHome", "添加书籍"))
        self.dropBookButton.setText(_translate("AdminHome", "淘汰书籍"))
        self.userManageButton.setText(_translate("AdminHome", "用户管理"))
        self.searchButton_2.setText(_translate("AdminHome", "查询"))
        self.comboBox_2.setItemText(0, _translate("AdminHome", "按书名查询"))
        self.comboBox_2.setItemText(1, _translate("AdminHome", "按书号查询"))
        self.comboBox_2.setItemText(2, _translate("AdminHome", "按作者查询"))
        self.comboBox_2.setItemText(3, _translate("AdminHome", "按分类查询"))
        self.comboBox_2.setItemText(4, _translate("AdminHome", "按出版社查询"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("AdminHome", "新建行"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("AdminHome", "1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("AdminHome", "2"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("AdminHome", "3"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("AdminHome", "4"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("AdminHome", "5"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("AdminHome", "6"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("AdminHome", "7"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("AdminHome", "8"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("AdminHome", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("AdminHome", "书名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("AdminHome", "书号"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("AdminHome", "作者"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("AdminHome", "分类"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("AdminHome", "出版社"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("AdminHome", "出版时间"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("AdminHome", "库存"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("AdminHome", "剩余可借"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("AdminHome", "总借阅次数"))
        self.jumpToLabel_2.setText(_translate("AdminHome", "跳转到第"))
        self.pageLabel_2.setText(_translate("AdminHome", "/5页"))
        self.jumpToButton_2.setText(_translate("AdminHome", "跳转"))
        self.prevButton_2.setText(_translate("AdminHome", "前一页"))
        self.backButton_2.setText(_translate("AdminHome", "后一页"))


