# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BorrowStatusViewer.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BorrowStatusViewer(object):
    def setupUi(self, BorrowStatusViewer):
        BorrowStatusViewer.setObjectName("BorrowStatusViewer")
        BorrowStatusViewer.resize(850, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(BorrowStatusViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.borrowedLabel = QtWidgets.QLabel(BorrowStatusViewer)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.borrowedLabel.setFont(font)
        self.borrowedLabel.setObjectName("borrowedLabel")
        self.verticalLayout.addWidget(self.borrowedLabel)
        self.borrowedTableView = QtWidgets.QTableWidget(BorrowStatusViewer)
        self.borrowedTableView.setObjectName("borrowedTableView")
        self.borrowedTableView.setColumnCount(7)
        self.borrowedTableView.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.borrowedTableView.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.borrowedTableView.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.borrowedTableView.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.borrowedTableView.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.borrowedTableView.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.borrowedTableView.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.borrowedTableView.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.borrowedTableView.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.borrowedTableView)
        self.returnedLabel = QtWidgets.QLabel(BorrowStatusViewer)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.returnedLabel.setFont(font)
        self.returnedLabel.setObjectName("returnedLabel")
        self.verticalLayout.addWidget(self.returnedLabel)
        self.returnedTableView = QtWidgets.QTableWidget(BorrowStatusViewer)
        self.returnedTableView.setObjectName("returnedTableView")
        self.returnedTableView.setColumnCount(8)
        self.returnedTableView.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.returnedTableView.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.returnedTableView.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.returnedTableView.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.returnedTableView.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.returnedTableView.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.returnedTableView.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.returnedTableView.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.returnedTableView.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.returnedTableView.setHorizontalHeaderItem(7, item)
        self.verticalLayout.addWidget(self.returnedTableView)

        self.retranslateUi(BorrowStatusViewer)
        QtCore.QMetaObject.connectSlotsByName(BorrowStatusViewer)

    def retranslateUi(self, BorrowStatusViewer):
        _translate = QtCore.QCoreApplication.translate
        BorrowStatusViewer.setWindowTitle(_translate("BorrowStatusViewer", "欢迎使用图书馆管理系统"))
        self.borrowedLabel.setText(_translate("BorrowStatusViewer", "未归还:"))
        item = self.borrowedTableView.verticalHeaderItem(0)
        item.setText(_translate("BorrowStatusViewer", "1"))
        item = self.borrowedTableView.horizontalHeaderItem(0)
        item.setText(_translate("BorrowStatusViewer", "书名"))
        item = self.borrowedTableView.horizontalHeaderItem(1)
        item.setText(_translate("BorrowStatusViewer", "书号"))
        item = self.borrowedTableView.horizontalHeaderItem(2)
        item.setText(_translate("BorrowStatusViewer", "作者"))
        item = self.borrowedTableView.horizontalHeaderItem(3)
        item.setText(_translate("BorrowStatusViewer", "分类"))
        item = self.borrowedTableView.horizontalHeaderItem(4)
        item.setText(_translate("BorrowStatusViewer", "出版社"))
        item = self.borrowedTableView.horizontalHeaderItem(5)
        item.setText(_translate("BorrowStatusViewer", "出版时间"))
        item = self.borrowedTableView.horizontalHeaderItem(6)
        item.setText(_translate("BorrowStatusViewer", "借出时间"))
        self.returnedLabel.setText(_translate("BorrowStatusViewer", "已归还:"))
        item = self.returnedTableView.verticalHeaderItem(0)
        item.setText(_translate("BorrowStatusViewer", "1"))
        item = self.returnedTableView.horizontalHeaderItem(0)
        item.setText(_translate("BorrowStatusViewer", "书名"))
        item = self.returnedTableView.horizontalHeaderItem(1)
        item.setText(_translate("BorrowStatusViewer", "书号"))
        item = self.returnedTableView.horizontalHeaderItem(2)
        item.setText(_translate("BorrowStatusViewer", "作者"))
        item = self.returnedTableView.horizontalHeaderItem(3)
        item.setText(_translate("BorrowStatusViewer", "分类"))
        item = self.returnedTableView.horizontalHeaderItem(4)
        item.setText(_translate("BorrowStatusViewer", "出版社"))
        item = self.returnedTableView.horizontalHeaderItem(5)
        item.setText(_translate("BorrowStatusViewer", "出版时间"))
        item = self.returnedTableView.horizontalHeaderItem(6)
        item.setText(_translate("BorrowStatusViewer", "借出时间"))
        item = self.returnedTableView.horizontalHeaderItem(7)
        item.setText(_translate("BorrowStatusViewer", "归还时间"))


