# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dropBookDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dropBookDialog(object):
    def setupUi(self, dropBookDialog):
        dropBookDialog.setObjectName("dropBookDialog")
        dropBookDialog.resize(329, 419)
        self.formLayout = QtWidgets.QFormLayout(dropBookDialog)
        self.formLayout.setObjectName("formLayout")
        self.titlelabel = QtWidgets.QLabel(dropBookDialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.titlelabel.setFont(font)
        self.titlelabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titlelabel.setLineWidth(1)
        self.titlelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titlelabel.setObjectName("titlelabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.titlelabel)
        self.bookNameLabel = QtWidgets.QLabel(dropBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bookNameLabel.setFont(font)
        self.bookNameLabel.setObjectName("bookNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bookNameLabel)
        self.bookNameEdit = QtWidgets.QLineEdit(dropBookDialog)
        self.bookNameEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bookNameEdit.setFont(font)
        self.bookNameEdit.setStyleSheet("#363636")
        self.bookNameEdit.setMaxLength(10)
        self.bookNameEdit.setObjectName("bookNameEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bookNameEdit)
        self.bookIdLabel = QtWidgets.QLabel(dropBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bookIdLabel.setFont(font)
        self.bookIdLabel.setObjectName("bookIdLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bookIdLabel)
        self.bookIdEdit = QtWidgets.QLineEdit(dropBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bookIdEdit.setFont(font)
        self.bookIdEdit.setMaxLength(6)
        self.bookIdEdit.setObjectName("bookIdEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bookIdEdit)
        self.authNameLabel = QtWidgets.QLabel(dropBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.authNameLabel.setFont(font)
        self.authNameLabel.setObjectName("authNameLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.authNameLabel)
        self.authNameEdit = QtWidgets.QLineEdit(dropBookDialog)
        self.authNameEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.authNameEdit.setFont(font)
        self.authNameEdit.setStyleSheet("#363636")
        self.authNameEdit.setMaxLength(10)
        self.authNameEdit.setObjectName("authNameEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.authNameEdit)
        self.categoryLabel = QtWidgets.QLabel(dropBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.categoryLabel.setFont(font)
        self.categoryLabel.setObjectName("categoryLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.categoryLabel)
        self.categoryComboBox = QtWidgets.QComboBox(dropBookDialog)
        self.categoryComboBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.categoryComboBox.setFont(font)
        self.categoryComboBox.setStyleSheet("#363636")
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.categoryComboBox)
        self.publisherLabel = QtWidgets.QLabel(dropBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.publisherLabel.setFont(font)
        self.publisherLabel.setObjectName("publisherLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.publisherLabel)
        self.publisherEdit = QtWidgets.QLineEdit(dropBookDialog)
        self.publisherEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.publisherEdit.setFont(font)
        self.publisherEdit.setStyleSheet("#363636")
        self.publisherEdit.setMaxLength(10)
        self.publisherEdit.setObjectName("publisherEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.publisherEdit)
        self.publishDateLabel = QtWidgets.QLabel(dropBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.publishDateLabel.setFont(font)
        self.publishDateLabel.setObjectName("publishDateLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.publishDateLabel)
        self.publishTime = QtWidgets.QDateEdit(dropBookDialog)
        self.publishTime.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.publishTime.setFont(font)
        self.publishTime.setStyleSheet("#363636")
        self.publishTime.setObjectName("publishTime")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.publishTime)
        self.dropNumLabel = QtWidgets.QLabel(dropBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dropNumLabel.setFont(font)
        self.dropNumLabel.setObjectName("dropNumLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.dropNumLabel)
        self.dropNumEdit = QtWidgets.QLineEdit(dropBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dropNumEdit.setFont(font)
        self.dropNumEdit.setMaxLength(12)
        self.dropNumEdit.setObjectName("dropNumEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.dropNumEdit)
        self.dropBookButton = QtWidgets.QPushButton(dropBookDialog)
        self.dropBookButton.setMaximumSize(QtCore.QSize(140, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dropBookButton.setFont(font)
        self.dropBookButton.setObjectName("dropBookButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.dropBookButton)

        self.retranslateUi(dropBookDialog)
        QtCore.QMetaObject.connectSlotsByName(dropBookDialog)

    def retranslateUi(self, dropBookDialog):
        _translate = QtCore.QCoreApplication.translate
        dropBookDialog.setWindowTitle(_translate("dropBookDialog", "删除书籍"))
        self.titlelabel.setText(_translate("dropBookDialog", "淘汰书籍"))
        self.bookNameLabel.setText(_translate("dropBookDialog", "书    名:"))
        self.bookIdLabel.setText(_translate("dropBookDialog", "书    号:"))
        self.authNameLabel.setText(_translate("dropBookDialog", "作    者:"))
        self.categoryLabel.setText(_translate("dropBookDialog", "分    类:"))
        self.categoryComboBox.setItemText(0, _translate("dropBookDialog", "哲学"))
        self.categoryComboBox.setItemText(1, _translate("dropBookDialog", "社会科学"))
        self.categoryComboBox.setItemText(2, _translate("dropBookDialog", "政治"))
        self.categoryComboBox.setItemText(3, _translate("dropBookDialog", "法律"))
        self.categoryComboBox.setItemText(4, _translate("dropBookDialog", "军事"))
        self.categoryComboBox.setItemText(5, _translate("dropBookDialog", "经济"))
        self.categoryComboBox.setItemText(6, _translate("dropBookDialog", "文化"))
        self.categoryComboBox.setItemText(7, _translate("dropBookDialog", "教育"))
        self.categoryComboBox.setItemText(8, _translate("dropBookDialog", "体育"))
        self.categoryComboBox.setItemText(9, _translate("dropBookDialog", "语言文字"))
        self.categoryComboBox.setItemText(10, _translate("dropBookDialog", "艺术"))
        self.categoryComboBox.setItemText(11, _translate("dropBookDialog", "历史"))
        self.categoryComboBox.setItemText(12, _translate("dropBookDialog", "地理"))
        self.categoryComboBox.setItemText(13, _translate("dropBookDialog", "天文学"))
        self.categoryComboBox.setItemText(14, _translate("dropBookDialog", "生物学"))
        self.categoryComboBox.setItemText(15, _translate("dropBookDialog", "医学卫生"))
        self.categoryComboBox.setItemText(16, _translate("dropBookDialog", "农业"))
        self.publisherLabel.setText(_translate("dropBookDialog", "出 版 社:"))
        self.publishDateLabel.setText(_translate("dropBookDialog", "出版日期:"))
        self.dropNumLabel.setText(_translate("dropBookDialog", "数    量:"))
        self.dropBookButton.setText(_translate("dropBookDialog", "淘 汰"))


