# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignUp.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignUpWidget(object):
    def setupUi(self, SignUpWidget):
        SignUpWidget.setObjectName("SignUpWidget")
        SignUpWidget.setWindowModality(QtCore.Qt.WindowModal)
        SignUpWidget.setEnabled(True)
        SignUpWidget.resize(1200, 600)
        SignUpWidget.setMinimumSize(QtCore.QSize(0, 0))
        SignUpWidget.setMaximumSize(QtCore.QSize(1201, 600))
        SignUpWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        SignUpWidget.setStyleSheet("")
        self.formLayout_4 = QtWidgets.QFormLayout(SignUpWidget)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setSpacing(0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, 0, 50)
        self.verticalLayout.setSpacing(160)
        self.verticalLayout.setObjectName("verticalLayout")
        self.signUpLabel = QtWidgets.QLabel(SignUpWidget)
        self.signUpLabel.setMinimumSize(QtCore.QSize(180, 32))
        self.signUpLabel.setMaximumSize(QtCore.QSize(1200, 600))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.signUpLabel.setFont(font)
        self.signUpLabel.setLineWidth(1)
        self.signUpLabel.setTextFormat(QtCore.Qt.AutoText)
        self.signUpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.signUpLabel.setObjectName("signUpLabel")
        self.verticalLayout.addWidget(self.signUpLabel)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_3.setHorizontalSpacing(0)
        self.formLayout_3.setVerticalSpacing(10)
        self.formLayout_3.setObjectName("formLayout_3")
        self.studentIdLabel = QtWidgets.QLabel(SignUpWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.studentIdLabel.setFont(font)
        self.studentIdLabel.setObjectName("studentIdLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.studentIdLabel)
        self.studentIdLineEdit = QtWidgets.QLineEdit(SignUpWidget)
        self.studentIdLineEdit.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.studentIdLineEdit.setFont(font)
        self.studentIdLineEdit.setInputMask("")
        self.studentIdLineEdit.setText("")
        self.studentIdLineEdit.setMaxLength(12)
        self.studentIdLineEdit.setDragEnabled(False)
        self.studentIdLineEdit.setPlaceholderText("")
        self.studentIdLineEdit.setObjectName("studentIdLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.studentIdLineEdit)
        self.studentNameLabel = QtWidgets.QLabel(SignUpWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.studentNameLabel.setFont(font)
        self.studentNameLabel.setObjectName("studentNameLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.studentNameLabel)
        self.studentNameLineEdit = QtWidgets.QLineEdit(SignUpWidget)
        self.studentNameLineEdit.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.studentNameLineEdit.setFont(font)
        self.studentNameLineEdit.setMaxLength(10)
        self.studentNameLineEdit.setObjectName("studentNameLineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.studentNameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(SignUpWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(SignUpWidget)
        self.passwordLineEdit.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setMaxLength(16)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.passwordConfirmLabel = QtWidgets.QLabel(SignUpWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.passwordConfirmLabel.setFont(font)
        self.passwordConfirmLabel.setObjectName("passwordConfirmLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.passwordConfirmLabel)
        self.passwordConfirmLineEdit = QtWidgets.QLineEdit(SignUpWidget)
        self.passwordConfirmLineEdit.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.passwordConfirmLineEdit.setFont(font)
        self.passwordConfirmLineEdit.setMaxLength(16)
        self.passwordConfirmLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordConfirmLineEdit.setObjectName("passwordConfirmLineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passwordConfirmLineEdit)
        self.signUpbutton = QtWidgets.QPushButton(SignUpWidget)
        self.signUpbutton.setMinimumSize(QtCore.QSize(120, 30))
        self.signUpbutton.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.signUpbutton.setFont(font)
        self.signUpbutton.setObjectName("signUpbutton")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.signUpbutton)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)

        self.retranslateUi(SignUpWidget)
        QtCore.QMetaObject.connectSlotsByName(SignUpWidget)

    def retranslateUi(self, SignUpWidget):
        _translate = QtCore.QCoreApplication.translate
        SignUpWidget.setWindowTitle(_translate("SignUpWidget", "欢迎登陆图书馆管理系统"))
        self.signUpLabel.setText(_translate("SignUpWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">注 册</span></p></body></html>"))
        self.studentIdLabel.setText(_translate("SignUpWidget", "学  号:"))
        self.studentNameLabel.setText(_translate("SignUpWidget", "姓  名: "))
        self.passwordLabel.setText(_translate("SignUpWidget", "密  码: "))
        self.passwordConfirmLabel.setText(_translate("SignUpWidget", "确认密码: "))
        self.signUpbutton.setText(_translate("SignUpWidget", "注 册"))


