# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StudentHome.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StudentHome(object):
    def setupUi(self, StudentHome):
        StudentHome.setObjectName("StudentHome")
        StudentHome.resize(1200, 600)
        self.gridWidget = QtWidgets.QWidget(StudentHome)
        self.gridWidget.setGeometry(QtCore.QRect(-6, 10, 110, 582))
        self.gridWidget.setObjectName("gridWidget")
        self.buttonlayout = QtWidgets.QGridLayout(self.gridWidget)
        self.buttonlayout.setContentsMargins(0, 0, 0, 0)
        self.buttonlayout.setObjectName("buttonlayout")
        self.myBookStatus = QtWidgets.QPushButton(self.gridWidget)
        self.myBookStatus.setMaximumSize(QtCore.QSize(100, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.myBookStatus.setFont(font)
        self.myBookStatus.setObjectName("myBookStatus")
        self.buttonlayout.addWidget(self.myBookStatus, 2, 0, 1, 1)
        self.returnBookButton = QtWidgets.QPushButton(self.gridWidget)
        self.returnBookButton.setMaximumSize(QtCore.QSize(100, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.returnBookButton.setFont(font)
        self.returnBookButton.setObjectName("returnBookButton")
        self.buttonlayout.addWidget(self.returnBookButton, 1, 0, 1, 1)
        self.borrowBookButton = QtWidgets.QPushButton(self.gridWidget)
        self.borrowBookButton.setEnabled(True)
        self.borrowBookButton.setMaximumSize(QtCore.QSize(100, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.borrowBookButton.setFont(font)
        self.borrowBookButton.setObjectName("borrowBookButton")
        self.buttonlayout.addWidget(self.borrowBookButton, 0, 0, 1, 1)
        self.allBookButton = QtWidgets.QPushButton(self.gridWidget)
        self.allBookButton.setMaximumSize(QtCore.QSize(100, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.allBookButton.setFont(font)
        self.allBookButton.setObjectName("allBookButton")
        self.buttonlayout.addWidget(self.allBookButton, 3, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(StudentHome)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 10, 766, 582))
        self.layoutWidget.setObjectName("layoutWidget")
        self.BookStorageViewer = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.BookStorageViewer.setContentsMargins(0, 0, 0, 0)
        self.BookStorageViewer.setObjectName("BookStorageViewer")
        self.Hlayout1_2 = QtWidgets.QHBoxLayout()
        self.Hlayout1_2.setObjectName("Hlayout1_2")
        self.searchEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.searchEdit_2.setFont(font)
        self.searchEdit_2.setObjectName("searchEdit_2")
        self.Hlayout1_2.addWidget(self.searchEdit_2)
        self.searchButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.searchButton_2.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.searchButton_2.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/syx/.designer/images/search.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.searchButton_2.setIcon(icon)
        self.searchButton_2.setObjectName("searchButton_2")
        self.Hlayout1_2.addWidget(self.searchButton_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 32))
        self.comboBox_2.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.Hlayout1_2.addWidget(self.comboBox_2)
        self.BookStorageViewer.addLayout(self.Hlayout1_2)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.BookStorageViewer.addWidget(self.tableWidget)
        self.horizontalWidget = QtWidgets.QWidget(self.layoutWidget)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.horizontalWidget)
        self.widget_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.Hlayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.Hlayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.Hlayout_2.setObjectName("Hlayout_2")
        self.jumpToLabel_2 = QtWidgets.QLabel(self.widget_2)
        self.jumpToLabel_2.setObjectName("jumpToLabel_2")
        self.Hlayout_2.addWidget(self.jumpToLabel_2)
        self.pageEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        self.pageEdit_2.setMaximumSize(QtCore.QSize(32, 16777215))
        self.pageEdit_2.setObjectName("pageEdit_2")
        self.Hlayout_2.addWidget(self.pageEdit_2)
        self.pageLabel_2 = QtWidgets.QLabel(self.widget_2)
        self.pageLabel_2.setObjectName("pageLabel_2")
        self.Hlayout_2.addWidget(self.pageLabel_2)
        self.jumpToButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.jumpToButton_2.setObjectName("jumpToButton_2")
        self.Hlayout_2.addWidget(self.jumpToButton_2)
        self.prevButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.prevButton_2.setObjectName("prevButton_2")
        self.Hlayout_2.addWidget(self.prevButton_2)
        self.backButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.backButton_2.setObjectName("backButton_2")
        self.Hlayout_2.addWidget(self.backButton_2)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.BookStorageViewer.addWidget(self.horizontalWidget)

        self.retranslateUi(StudentHome)
        QtCore.QMetaObject.connectSlotsByName(StudentHome)

    def retranslateUi(self, StudentHome):
        _translate = QtCore.QCoreApplication.translate
        StudentHome.setWindowTitle(_translate("StudentHome", "欢迎使用图书馆管理系统"))
        self.myBookStatus.setText(_translate("StudentHome", "借阅状态"))
        self.returnBookButton.setText(_translate("StudentHome", "还书"))
        self.borrowBookButton.setText(_translate("StudentHome", "借书"))
        self.allBookButton.setText(_translate("StudentHome", "所有书籍"))
        self.searchButton_2.setText(_translate("StudentHome", "查询"))
        self.comboBox_2.setItemText(0, _translate("StudentHome", "按书名查询"))
        self.comboBox_2.setItemText(1, _translate("StudentHome", "按书号查询"))
        self.comboBox_2.setItemText(2, _translate("StudentHome", "按作者查询"))
        self.comboBox_2.setItemText(3, _translate("StudentHome", "按分类查询"))
        self.comboBox_2.setItemText(4, _translate("StudentHome", "按出版社查询"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("StudentHome", "新建行"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("StudentHome", "1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("StudentHome", "2"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("StudentHome", "3"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("StudentHome", "4"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("StudentHome", "5"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("StudentHome", "6"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("StudentHome", "7"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("StudentHome", "8"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("StudentHome", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("StudentHome", "书名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("StudentHome", "书号"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("StudentHome", "作者"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("StudentHome", "分类"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("StudentHome", "出版社"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("StudentHome", "出版时间"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("StudentHome", "库存"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("StudentHome", "剩余可借"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("StudentHome", "总借阅次数"))
        self.jumpToLabel_2.setText(_translate("StudentHome", "跳转到第"))
        self.pageLabel_2.setText(_translate("StudentHome", "/5页"))
        self.jumpToButton_2.setText(_translate("StudentHome", "跳转"))
        self.prevButton_2.setText(_translate("StudentHome", "前一页"))
        self.backButton_2.setText(_translate("StudentHome", "后一页"))


