# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'returnBookDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_returnBookDialog(object):
    def setupUi(self, returnBookDialog):
        returnBookDialog.setObjectName("returnBookDialog")
        returnBookDialog.resize(300, 400)
        self.formLayout = QtWidgets.QFormLayout(returnBookDialog)
        self.formLayout.setObjectName("formLayout")
        self.titlelabel = QtWidgets.QLabel(returnBookDialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.titlelabel.setFont(font)
        self.titlelabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titlelabel.setLineWidth(1)
        self.titlelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titlelabel.setObjectName("titlelabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.titlelabel)
        self.returnStudentLabel = QtWidgets.QLabel(returnBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.returnStudentLabel.setFont(font)
        self.returnStudentLabel.setObjectName("returnStudentLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.returnStudentLabel)
        self.bookNameLabel = QtWidgets.QLabel(returnBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bookNameLabel.setFont(font)
        self.bookNameLabel.setObjectName("bookNameLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bookNameLabel)
        self.bookNameEdit = QtWidgets.QLineEdit(returnBookDialog)
        self.bookNameEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bookNameEdit.setFont(font)
        self.bookNameEdit.setStyleSheet("#363636")
        self.bookNameEdit.setMaxLength(10)
        self.bookNameEdit.setObjectName("bookNameEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bookNameEdit)
        self.bookIdLabel = QtWidgets.QLabel(returnBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bookIdLabel.setFont(font)
        self.bookIdLabel.setObjectName("bookIdLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bookIdLabel)
        self.bookIdEdit = QtWidgets.QLineEdit(returnBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bookIdEdit.setFont(font)
        self.bookIdEdit.setMaxLength(6)
        self.bookIdEdit.setObjectName("bookIdEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bookIdEdit)
        self.authNameLabel = QtWidgets.QLabel(returnBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.authNameLabel.setFont(font)
        self.authNameLabel.setObjectName("authNameLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.authNameLabel)
        self.authNameEdit = QtWidgets.QLineEdit(returnBookDialog)
        self.authNameEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.authNameEdit.setFont(font)
        self.authNameEdit.setStyleSheet("#363636")
        self.authNameEdit.setMaxLength(10)
        self.authNameEdit.setObjectName("authNameEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.authNameEdit)
        self.categoryLabel = QtWidgets.QLabel(returnBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.categoryLabel.setFont(font)
        self.categoryLabel.setObjectName("categoryLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.categoryLabel)
        self.categoryComboBox = QtWidgets.QComboBox(returnBookDialog)
        self.categoryComboBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.categoryComboBox.setFont(font)
        self.categoryComboBox.setStyleSheet("#363636")
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.categoryComboBox)
        self.publisherLabel = QtWidgets.QLabel(returnBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.publisherLabel.setFont(font)
        self.publisherLabel.setObjectName("publisherLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.publisherLabel)
        self.publisherEdit = QtWidgets.QLineEdit(returnBookDialog)
        self.publisherEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.publisherEdit.setFont(font)
        self.publisherEdit.setStyleSheet("#363636")
        self.publisherEdit.setMaxLength(10)
        self.publisherEdit.setObjectName("publisherEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.publisherEdit)
        self.publishDateLabel = QtWidgets.QLabel(returnBookDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.publishDateLabel.setFont(font)
        self.publishDateLabel.setObjectName("publishDateLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.publishDateLabel)
        self.publishTime = QtWidgets.QDateEdit(returnBookDialog)
        self.publishTime.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.publishTime.setFont(font)
        self.publishTime.setStyleSheet("#363636")
        self.publishTime.setObjectName("publishTime")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.publishTime)
        self.returnBookButton = QtWidgets.QPushButton(returnBookDialog)
        self.returnBookButton.setMaximumSize(QtCore.QSize(140, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.returnBookButton.setFont(font)
        self.returnBookButton.setObjectName("returnBookButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.returnBookButton)

        self.retranslateUi(returnBookDialog)
        QtCore.QMetaObject.connectSlotsByName(returnBookDialog)

    def retranslateUi(self, returnBookDialog):
        _translate = QtCore.QCoreApplication.translate
        returnBookDialog.setWindowTitle(_translate("returnBookDialog", "归还书籍"))
        self.titlelabel.setText(_translate("returnBookDialog", "归还书籍"))
        self.returnStudentLabel.setText(_translate("returnBookDialog", "还 书 人:"))
        self.bookNameLabel.setText(_translate("returnBookDialog", "书    名:"))
        self.bookIdLabel.setText(_translate("returnBookDialog", "书    号:"))
        self.authNameLabel.setText(_translate("returnBookDialog", "作    者:"))
        self.categoryLabel.setText(_translate("returnBookDialog", "分    类:"))
        self.categoryComboBox.setItemText(0, _translate("returnBookDialog", "哲学"))
        self.categoryComboBox.setItemText(1, _translate("returnBookDialog", "社会科学"))
        self.categoryComboBox.setItemText(2, _translate("returnBookDialog", "政治"))
        self.categoryComboBox.setItemText(3, _translate("returnBookDialog", "法律"))
        self.categoryComboBox.setItemText(4, _translate("returnBookDialog", "军事"))
        self.categoryComboBox.setItemText(5, _translate("returnBookDialog", "经济"))
        self.categoryComboBox.setItemText(6, _translate("returnBookDialog", "文化"))
        self.categoryComboBox.setItemText(7, _translate("returnBookDialog", "教育"))
        self.categoryComboBox.setItemText(8, _translate("returnBookDialog", "体育"))
        self.categoryComboBox.setItemText(9, _translate("returnBookDialog", "语言文字"))
        self.categoryComboBox.setItemText(10, _translate("returnBookDialog", "艺术"))
        self.categoryComboBox.setItemText(11, _translate("returnBookDialog", "历史"))
        self.categoryComboBox.setItemText(12, _translate("returnBookDialog", "地理"))
        self.categoryComboBox.setItemText(13, _translate("returnBookDialog", "天文学"))
        self.categoryComboBox.setItemText(14, _translate("returnBookDialog", "生物学"))
        self.categoryComboBox.setItemText(15, _translate("returnBookDialog", "医学卫生"))
        self.categoryComboBox.setItemText(16, _translate("returnBookDialog", "农业"))
        self.publisherLabel.setText(_translate("returnBookDialog", "出 版 社:"))
        self.publishDateLabel.setText(_translate("returnBookDialog", "出版日期:"))
        self.returnBookButton.setText(_translate("returnBookDialog", "确认归还"))


